### ISSUE TITLE
Checkpoint 3

### ISSUE THREAD

**Issue by tvdmitrii** [tvdmitrii/courseSchedulePlanner-api#7]
@pawaitemadisoncollege checkpoint 3 is complete.

- [X] Deployed to AWS
> Here is a [link](https://csp-tomcat-10-1-env.eba-uyvpbhrz.us-east-2.elasticbeanstalk.com/) just in case. I have HTTPs working with a self-signed certificate and it is running on new and shiny Tomcat 10.1!
- [X] At least one JSP that displays data from the database is implemented.
> The main page allows searching for courses by department and/or course title and view detailed information about the courses. All data comes from the database.
- [X] Authentication implemented.
> Admittedly, this point is arguable. I have Cognito authentication logic implement, the REST API endpoint for adding/fetching user information from the database is there, but it is not yet connected to the web application. The website does not take advantage of this functionality yet. I decided to significantly rework the provided code used for fetching the JWT from Cognito and validating it. I have switched from `HttpClient` to Jersey's REST API client to fetch the JWT token. It ends up being, in my opinion, a bit cleaner and simpler. I have also replaced the custom validation logic and JWKS fetching with `com.auth0.jwks-rsa` package and its `JwkProvider`. The results of this work can be found in `com.turygin.cognito` package and `com.turygin.servlert.WebAppStartup` class. It is very neat, but it took some time to figure it out.

I have also added the links to all of my repositories used in the project and the deployed application to [IndividualProjects in shared student repository](https://github.com/mad-ent-java-f24/student/blob/main/IndividualProjects.md).

**Comment by pawaitemadisoncollege** [comment]
Wow @tvdmitrii! You've done a lot of great work here and clearly have put in a lot of time and thought on your indie project so far! I appreciate that you are exploring clean, simple solutions!

You had asked about your indie project counting for the service work and this clearly meets that for week 8 and 9. Your work on the team project so far meets week 9 too, so I'll check those off in Blackboard. 

Let me know when I can test out the sign up/log in functionality by replying to this issue and I'll finalize the mark for Checkpoint 3 in Blackboard as well!

**Comment by tvdmitrii** [comment]
Thank you, @pawaitemadisoncollege!

I have added the login functionality to my [demo website](https://csp-tomcat-10-1-env.eba-uyvpbhrz.us-east-2.elasticbeanstalk.com). Whenever you login the web app will:
- Hide the login link
- Show additional navigation buttons including Log out
- Display a greeting "Welcome, `firstName`!". It gets `firstName` from Cognito.

Once you log out, the interface returns back to normal, and the internal session variable holding user information is cleared.

You can either create a new account or use one I created:
- Username: `random`
- Password: `sSQxzLnR4rc7d@vx~saViw^jj$M#4~mJ`

**Comment by pawaitemadisoncollege** [comment]
Looks good @tvdmitrii - I was able to sign up and log in successfully with my name showing on the main page. Good work! 

CP 3: met
