### ISSUE TITLE
Code Complete

### ISSUE THREAD

**Issue by tvdmitrii** [tvdmitrii/courseSchedulePlanner-api#8]
@pawaitemadisoncollege, I am excited to say that my individual project is code complete and ready for review! I was able to achieve everything I set out to do for an MVP.

**Code**
The code has been all pushed to [REST API back-end repo](https://github.com/tvdmitrii/courseSchedulePlanner-api), [WebApp front-end repo](https://github.com/tvdmitrii/courseSchedulePlanner-webApp), and the [REST API Interface repo](https://github.com/tvdmitrii/courseSchedulePlanner-interface).

**Demo**
The [code is live on AWS](https://csp-tomcat-10-1-env.eba-uyvpbhrz.us-east-2.elasticbeanstalk.com). The account you have created for checkpoint 3 should still work, however there is still regular user with username `random` and password `sSQxzLnR4rc7d@vx~saViw^jj$M#4~mJ` and an administrator user with username `dturygin` and password ``$cFjH5%m5QFjcEf`Pv&NV^kYW2EY`@Z3``. Administrator account is required to get access to "Edit Catalog" page which allows an administrator to add/edit/delete courses and course sections.

**Comment by pawaitemadisoncollege** [comment]
Hi @tvdmitrii! I often find doing a final code review is easiest/most efficient for me if I do it in as I watch the final project presentation.  I'm curious if you are planning to share that video soon (if I've overlooked it, please let me know)! Thanks!

**Comment by tvdmitrii** [comment]
Hi @pawaitemadisoncollege, of course! I will have my presentation ready on Monday, December 9th. I was hoping to get to it over the weekend, but, unfortunately, I have been busy wrapping up my other classes.

**Comment by pawaitemadisoncollege** [comment]
Hi @tvdmitrii! You did such a fantastic job with your individual project! You have lots to be proud of here - from the original project idea to the completed application. It demo-ed  beautifully in your presentation and it an excellent portfolio piece.  You clearly demonstrated all that you learned in Ent Java, in the web dev program, and beyond that, on your own. Some of the highlights related to the core competencies in this class (also refer to my observations posted in slack during your presentation):

You made good use of properties files to avoid exposing private keys to the public in github and to make it easy to maintain many values without a source code change. Using properties loader interface to avoid duplicate code blocks for loading properties, and doing work like this a single time in the application startup. Use of templating reusable jsp parts for easier maintenance and look and feel consistency. Generic DTO and DAO to avoid duplication. Methods are generally small and single-purpose. Appropriate use of ORM (hibernate). Consumes a restful api using java code to separate logic into maintainable, reusable, components. Generally well-documented for easier review and future maintenance. 

I share the following not to take anything at all away from your hard work, but rather to identify what might be next in terms of showing off your work, or as areas to consider in future development of any similar application.

- [ ] Consider adding screenshots or a short animated gif to your readme to really show off your application right when somebody accesses the repo. 

- [ ] I wonder if variables like these should also be static? https://github.com/tvdmitrii/courseSchedulePlanner-api/blob/08cd94abf78a20c6bd361ac4671cc1d2cd9be401/src/main/java/com/turygin/api/server/resource/CartResource.java#L24-L31

- [ ] In some cases, the list of import statements could be shortened by using a star to import everything in the package. Here it would save a few lines for example:  https://github.com/tvdmitrii/courseSchedulePlanner-api/blob/08cd94abf78a20c6bd361ac4671cc1d2cd9be401/src/main/java/com/turygin/api/server/resource/CourseResource.java#L3-L12. 

- [ ] Like many applications, unit testing could be more thorough. The hibernate entity DAOs are well-tested, but some key application logic could be better tested. The schedule building logic, for example, doesn't appear to be unit tested at this time. 

- [ ] I think it would be a good exercise to run one or more code quality tools on your codebase to inspect areas for possible tweaking. 

Congrats again on building this Schedule Planner. It's an impressive body of work! 

Lastly, thank you for your continued patience with my often late feedback this semester. I've had a bit too much on my work plate recently, and unfortunately the students who are pretty self-sufficient like you probably felt that the most.  

Enjoy winter break - I hope you have some quality time with your family!
