### ISSUE TITLE
Peer Review/Week 14

### ISSUE THREAD

**Issue by SapphireStar31** [tvdmitrii/courseSchedulePlanner-api#9]
@pawaitemadisoncollege
# Design/Code Review 2

#### Reviewer: Karissa Halverson

|Areas for Improvement|Criteria|Items Met or Exceeded|
|--------|---------|---------------|
||**Project effectively utilizes the technologies and techniques specified in the project objectives**| Met |
| Looks like all User Stories that were MVP were put into the application. | Planned MVP Functionality | Met |
|| Logging framework used, i.e., no System.out.println() or printStacktrace() statements.| Met |
|| Hibernate used for all data access. | Met |
| There is separate code for checking if a user is an admin or if they are a normal user. | Authentication implemented and adds value to the application. | Met |
| Created own API code for use on the Web app side which compliments exactly what was needed to finish the project. | Consumes at least one web service or public api using Java. | Exceeded |
|| Application is database-driven using full CRUD.| Met |
| Lots of different many to one relationships. | Database includes multiple one to many relationships. | Exceeded |
|| Deployed to AWS for public access. | Met |
| There are some classes that return null in the Cognito classes for the Web app which isn't a best practice, but everything else is looking good. | Implements best practices (for example, data validation)  | Almost Met |
|| **Synthesis of multiple concepts in unfamiliar situations requiring research beyond the scope of the class**| Met |
||Experiments individually, exhibits independence and drive, shows originality in the solution.| Met |
||Implemented technologies or techniques not covered in course materials. | Met |
||**Code quality - Evaluate  code quality for the following and identify specific areas for improvement (class, method or line number). Be sure to list which code quality plugins/tools you used to assist with this analysis**||
| Code is broken up so that each method has one job and makes many methods. | Single-purpose methods | Met |
| Lots of different packages depending on what the classes inside are doing. As well as different repositories for the different parts of the project. | Well-structured project| Exceeded |
| Each class a descriptive name so you can tell what it is most likely going to do before you open it up. Variables and Methods also have descriptive names. | Descriptive naming of packages, classes, methods, variables | Met |
||Classes appropriately-sized  (no monster classes)| Met |
| From looking through the code it doesn't seem like it. | CPD (copy paste detection, meaning are the same lines of code repeated?| Met |
|| Are there candidates for super/subclass relationships, abstract classes, interfaces | No |
| Seems like there are property files containing the hard coded values. Can't see the files, but from the code looks like they are floating around. | Are any values hard-coded that should be in a properties file? | No |
| Lots of different try catch blocks for handling exceptions where they are needed. |Proper exception handling | Met |
| Has little pop ups that appear when there is an error rather than a separate page showing the error. |Proper error reporting to the user - custom error pages?| Met | 
| Javadoc code for all classes and methods. Personally I wish there might be a little more explanation in the javadoc comments for some methods and classes, but thats just what I think. Most comments do say what each class or method is doing. |Code documentation| Met | 
|| Is there code in the servlet doGet/doPost that should be refactored into testable classes or methods? | No |
| Different templates for the JSPs. Has required on the forms where needed. |Evaluate the JSPs for templating, data validation, overall look and feel.| Met |
|| JSPs use JSTL and EL, no java code ||| Met |
| Checks for null values, different inserts, and different situations that need to be tested. | Unit tests are truly a unit test rather than a high level functional test | Met | 
||Test data is appropriately cleaned up or handled| Met | 
| Just looked through the tests and didn't run them personally, but looked like all classes got their code tested in different ways. |There is full coverage of methods that perform business logic or utility functions| Met |
||Redundant code is eliminated by using set up and tear down methods, i.e., @Before, @After| Met |
| Project is wonderfully done. |Other comments/notes?| |
||**Demonstrates initiative and thoughtful planning to leverage available resources (time, equipment, external expertise) to meet milestones and project objectives.** | Exceeded |
|| **Evidence of significant revision and incorporation of feedback.** ||
| Lots of commits on each of the repositories especially on the API one. Otherwise the other two have a good amount of commits on them as well.  | What does github history and insights demonstrate about the work on this project?| Met |
|| **Project complexity** ||
| Much more complicated than the User Display exercise. | Consider the user display exercise to be a simple project; how does this project compare? | Exceeded |
| Custom API, User Authentication and login with Cognito, Large database, HTML has a planner on it that shows the calendar and the classes on it, has interface, web app, and API repositories for all the code. | What aspects of the project add complexity? | Met |
| Thank you for letting me review your project Dmitrii! I learned a lot just looking through it. | **Additional Comments** ||

**Comment by pawaitemadisoncollege** [comment]
Hi @SapphireStar31 - thank you for your careful review of @tvdmitrii 's project.  I know he has been working hard to finish early so you really got to see a complete project in this review. It's great to read that you found it to be a learning opportunity! Your review is thorough and does a good job balancing positive feedback with areas for improvement. 

As I mentioned in Dmitrii's review feedback, using line numbers can be helpful in drawing the dev's attention to an example. Here is one case where I think an example could help the dev: "little more explanation in the javadoc comments for some methods and classes"

One thing that can be really helpful when reviewing projects like this is to use one or more of the code quality tools listed in the week 14 course materials.  While this can sometimes have a number of false positives, it can provide assistance in finding some best practices that we may overlook when "eyeballing" the project. 

You did a nice job with the review of a very complex project spanning multiple repositories - this will set you up really well  for doing similar work on the job!
